#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
MASTERBRANCH="master"

curl http://192.168.1.26:8080/jenkins/job/EMC_RESTAPP/build

echo "\n\nHi, Build triggered successfully on branch: $BRANCHNAME\n\n" 
