#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".
BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
MASTERBRANCH="master"

#if[ $BRANCHNAME = $MASTERBRANCH ]; then
	curl http://192.168.1.24:8080/jenkins/job/Test_REST/build
#else
#fi

echo "Hi, Build triggered successfully on branch: $BRANCHNAME" 
